version: '2'
services:
  spider:
    image: 'scrapy'
    volumes:
      - '$PWD/scrapy:/scrapy'
    networks:
      capture:
        ipv4_address: $SCRAPY_IP
    command: sleep 10000000 #scrapy runspider 'scrapy/spider.py'

####################################################################################################################
####################################################################################################################

  tcpdump_spider:
    image: 'detlearsom/tcpdump'
    command: not(ip6 or arp or (udp and (src port 5353 or src port 57621))) -v -w "/data/${PROJECT_NAME}_spider-${CAPTURETIME}-sc${SCENARIO}-$REPNUM.pcap"
    volumes:
      - '${DATADIR}:/data'
    network_mode: "service:spider"

  # tcpdump_relay_endpoint:
  #   image: 'detlearsom/tcpdump'
  #   #container_name: tcpdump_relay_stepstone
  #   command: not(ip6 or arp or (udp and (src port 5353 or src port 57621))) -v -w "/data/${PROJECT_NAME}_relay_endpoint-${CAPTURETIME}-sc${SCENARIO}-$REPNUM.pcap"
  #   volumes:
  #     - '${DATADIR}:/data'
  #   depends_on:
  #     - dummy
  #   network_mode: "service:relay_endpoint"

  # tcpdump_spider:
  #   image: 'detlearsom/tcpdump'
  #   #container_name: tcpdump_relay_stepstone
  #   command: not(ip6 or arp or (udp and (src port 5353 or src port 57621))) -v -w "/data/${PROJECT_NAME}_spider-${CAPTURETIME}-sc${SCENARIO}-$REPNUM.pcap"
  #   volumes:
  #     - '${DATADIR}:/data'
  #   depends_on:
  #     - dummy
  #   network_mode: "service:spider"

####################################################################################################################
####################################################################################################################

networks:
  capture:
    driver: "bridge"
    ipam:
      driver: default
      config:
      - subnet: 172.${IP_RANGE}.238.0/24
        gateway: 172.${IP_RANGE}.238.1
